Repository bflad/tfproviderlint, pull requests merged in 2019-06, with the labels that each got.

#21 Add R004: check for `ResourceData.Set()` calls using incompatible value types
  README.md
  cmd/tfproviderlint/tfproviderlint.go
  passes/R004/R004.go
  passes/R004/R004_test.go
  passes/R004/testdata/src/a/alias.go
  passes/R004/testdata/src/a/comment_ignore.go
  passes/R004/testdata/src/a/main.go
  passes/R004/testdata/src/a/outside_package.go
  passes/R004/testdata/src/a/schema/schema.go
  passes/R004/testdata/src/vendor
Labels: ast, check/resource, new-check

#24 Adding schemamap to linter
  helper/terraformtype/terraformtype.go
  passes/S001/S001.go
  passes/S001/testdata/src/a/alias.go
  passes/S001/testdata/src/a/main.go
  passes/S001/testdata/src/a/outside_package.go
  passes/S002/S002.go
  passes/S002/testdata/src/a/alias.go
  passes/S002/testdata/src/a/main.go
  passes/S002/testdata/src/a/outside_package.go
  passes/S003/S003.go
  passes/S003/testdata/src/a/alias.go
  passes/S003/testdata/src/a/main.go
  passes/S003/testdata/src/a/outside_package.go
  passes/S004/S004.go
  passes/S004/testdata/src/a/alias.go
  passes/S004/testdata/src/a/main.go
  passes/S004/testdata/src/a/outside_package.go
  passes/S005/S005.go
  passes/S005/testdata/src/a/alias.go
  passes/S005/testdata/src/a/main.go
  passes/S005/testdata/src/a/outside_package.go
  passes/S006/S006.go
  passes/S006/testdata/src/a/alias.go
  passes/S006/testdata/src/a/main.go
  passes/S006/testdata/src/a/outside_package.go
  passes/schemamap/README.md
  passes/schemamap/schemamap.go
  passes/schemaschema/schemaschema.go
Labels: ast, check/schema, enhancement

#25 passes/AT001: Ignore file names beginning with data_source_
  passes/AT001/AT001.go
  passes/AT001/README.md
  passes/AT001/testdata/src/a/data_source_prefix_ignore.go
Labels: ast, bug, check/acctest
