Repository bflad/tfproviderlint, pull requests merged in 2020-04, with the labels that each got.

#161 New Extra Check: XR005: check for Resource that Description is configured
  CHANGELOG.md
  README.md
  helper/terraformtype/helper/schema/type_resource.go
  xpasses/XR005/README.md
  xpasses/XR005/XR005.go
  xpasses/XR005/XR005_test.go
  xpasses/XR005/testdata/src/a/alias.go
  xpasses/XR005/testdata/src/a/main.go
  xpasses/XR005/testdata/src/a/outside_package.go
  xpasses/XR005/testdata/src/a/schema/schema.go
  xpasses/XR005/testdata/src/a/vendor
  xpasses/checks.go
Labels: ast, check/resource, new-check

#164 deps: Update golang.org/x/tools@master
  go.mod
  go.sum
  vendor/golang.org/x/tools/go/analysis/analysis.go
  vendor/golang.org/x/tools/go/analysis/analysistest/analysistest.go
  vendor/golang.org/x/tools/go/analysis/internal/checker/checker.go
  vendor/golang.org/x/tools/go/analysis/singlechecker/singlechecker.go
  vendor/golang.org/x/tools/go/ast/astutil/enclosing.go
  vendor/golang.org/x/tools/go/ast/astutil/imports.go
  vendor/golang.org/x/tools/go/ast/astutil/rewrite.go
  vendor/golang.org/x/tools/go/ast/astutil/util.go
  vendor/golang.org/x/tools/go/ast/inspector/inspector.go
  vendor/golang.org/x/tools/go/internal/packagesdriver/sizes.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/golist_overlay.go
  vendor/golang.org/x/tools/go/packages/loadmode_string.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/internal/analysisinternal/analysis.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/lsp/diff/diff.go
  vendor/golang.org/x/tools/internal/lsp/diff/unified.go
  vendor/golang.org/x/tools/internal/packagesinternal/packages.go
  vendor/golang.org/x/tools/internal/span/parse.go
  vendor/golang.org/x/tools/internal/span/span.go
  vendor/golang.org/x/tools/internal/span/token.go
  vendor/golang.org/x/tools/internal/span/token111.go
  vendor/golang.org/x/tools/internal/span/token112.go
  vendor/golang.org/x/tools/internal/span/uri.go
  vendor/golang.org/x/tools/internal/span/utf16.go
  vendor/golang.org/x/tools/internal/telemetry/event/event.go
  vendor/golang.org/x/tools/internal/telemetry/event/export.go
  vendor/golang.org/x/tools/internal/telemetry/event/key.go
  vendor/golang.org/x/tools/internal/telemetry/event/label.go
  vendor/golang.org/x/tools/internal/telemetry/event/log.go
  vendor/golang.org/x/tools/internal/telemetry/event/metric.go
  vendor/golang.org/x/tools/internal/telemetry/event/tag.go
  vendor/golang.org/x/tools/internal/telemetry/event/trace.go
  vendor/golang.org/x/xerrors/LICENSE
  vendor/golang.org/x/xerrors/PATENTS
  vendor/golang.org/x/xerrors/README
  vendor/golang.org/x/xerrors/adaptor.go
  vendor/golang.org/x/xerrors/codereview.cfg
  vendor/golang.org/x/xerrors/doc.go
  vendor/golang.org/x/xerrors/errors.go
  vendor/golang.org/x/xerrors/fmt.go
  vendor/golang.org/x/xerrors/format.go
  vendor/golang.org/x/xerrors/frame.go
  vendor/golang.org/x/xerrors/go.mod
  vendor/golang.org/x/xerrors/internal/internal.go
  vendor/golang.org/x/xerrors/wrap.go
  vendor/modules.txt
Labels: dependencies

#129 Link Resource and Schema to fill each other && test basic Schema
  helper/terraformtype/helper/schema/testdata/type_resource/resource.go
  helper/terraformtype/helper/schema/testdata/type_schema/schema.go
  helper/terraformtype/helper/schema/type_resource.go
  helper/terraformtype/helper/schema/type_resource_test.go
  helper/terraformtype/helper/schema/type_schema.go
  helper/terraformtype/helper/schema/type_schema_test.go
Labels: ast, enhancement

#165 Switch from helper/analysisfixtest to analysistest.RunWithSuggestedFixes
  CHANGELOG.md
  README.md
  go.mod
  helper/analysisfixtest/analysisfixtest.go
  passes/R007/R007_test.go
  passes/R007/testdata/src/a/main.go.golden
  passes/R008/R008_test.go
  passes/R008/testdata/src/a/main.go.golden
  passes/V002/V002_test.go
  passes/V002/testdata/src/a/alias.go.golden
  passes/V002/testdata/src/a/main.go.golden
  passes/V003/V003_test.go
  passes/V003/testdata/src/a/alias.go.golden
  passes/V003/testdata/src/a/main.go.golden
  passes/V004/V004_test.go
  passes/V004/testdata/src/a/alias.go.golden
  passes/V004/testdata/src/a/main.go.golden
  passes/V005/V005_test.go
  passes/V005/testdata/src/a/alias.go.golden
  passes/V005/testdata/src/a/main.go.golden
  passes/V006/V006_test.go
  passes/V006/testdata/src/a/alias.go.golden
  passes/V006/testdata/src/a/main.go.golden
  passes/V007/V007_test.go
  passes/V007/testdata/src/a/alias.go.golden
  passes/V007/testdata/src/a/main.go.golden
  passes/V008/V008_test.go
  passes/V008/testdata/src/a/alias.go.golden
  passes/V008/testdata/src/a/main.go.golden
  vendor/github.com/sergi/go-diff/AUTHORS
  vendor/github.com/sergi/go-diff/CONTRIBUTORS
  vendor/github.com/sergi/go-diff/LICENSE
  vendor/github.com/sergi/go-diff/diffmatchpatch/diff.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/diffmatchpatch.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/match.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/mathutil.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/patch.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/stringutil.go
  vendor/golang.org/x/tools/go/analysis/singlechecker/singlechecker.go
  vendor/modules.txt
Labels: ast, enhancement

#167 helper/terraformtype/helper/schema: Prevent panics in NewResourceInfo
  helper/terraformtype/helper/schema/testdata/type_resource/resource.go
  helper/terraformtype/helper/schema/type_resource.go
  helper/terraformtype/helper/schema/type_resource_test.go
Labels: ast, bug
